# Generated by Django 3.2.13 on 2022-05-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_word', models.CharField(max_length=100)),
                ('time_allowed', models.TimeField(null=True)),
                ('guesses_allowed', models.IntegerField(null=True)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('W', 'WON'), ('L', 'LOST')], max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hangmanword',
            name='difficulty',
            field=models.CharField(choices=[('H', 'HARD'), ('M', 'MEDIUM'), ('E', 'EASY')], default='H', max_length=1),
            preserve_default=False,
        ),
    ]
