# Generated by Django 3.2.13 on 2022-05-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_hangmangame_guessed_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangmangame',
            name='time_allowed',
            field=models.DurationField(null=True),
        ),
    ]
