# Generated by Django 3.2.13 on 2022-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_alter_hangmangame_time_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangmangame',
            name='guessed_letters',
            field=models.CharField(default='', max_length=26),
        ),
    ]
