# Generated by Django 3.2.13 on 2022-05-02 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_alter_hangmangame_guessed_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangmangame',
            name='guesses_allowed',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
    ]
