# Generated by Django 3.2.13 on 2022-05-03 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0006_alter_hangmangame_guesses_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangmangame',
            name='guesses_allowed',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
