# Generated by Django 3.2.13 on 2022-05-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('hangman', '0007_alter_hangmangame_guesses_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangmangame',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='profiles.profile'),
        ),
    ]
