# Generated by Django 3.2.13 on 2022-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0008_hangmangame_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangmangame',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
